// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_chunked_long
void read_chunked_long(CharacterVector filename, Environment callback, int chunksize, CharacterVector var_names, CharacterVector var_types, List rt_info_, List var_pos_info_, List var_opts_, bool isGzipped, CharacterVector encoding, bool progress);
RcppExport SEXP _hipread_read_chunked_long(SEXP filenameSEXP, SEXP callbackSEXP, SEXP chunksizeSEXP, SEXP var_namesSEXP, SEXP var_typesSEXP, SEXP rt_info_SEXP, SEXP var_pos_info_SEXP, SEXP var_opts_SEXP, SEXP isGzippedSEXP, SEXP encodingSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< Environment >::type callback(callbackSEXP);
    Rcpp::traits::input_parameter< int >::type chunksize(chunksizeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_names(var_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_types(var_typesSEXP);
    Rcpp::traits::input_parameter< List >::type rt_info_(rt_info_SEXP);
    Rcpp::traits::input_parameter< List >::type var_pos_info_(var_pos_info_SEXP);
    Rcpp::traits::input_parameter< List >::type var_opts_(var_opts_SEXP);
    Rcpp::traits::input_parameter< bool >::type isGzipped(isGzippedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type encoding(encodingSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    read_chunked_long(filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress);
    return R_NilValue;
END_RCPP
}
// read_long
RObject read_long(CharacterVector filename, CharacterVector var_names, CharacterVector var_types, List rt_info_, List var_pos_info_, List var_opts_, bool isGzipped, CharacterVector encoding, bool progress);
RcppExport SEXP _hipread_read_long(SEXP filenameSEXP, SEXP var_namesSEXP, SEXP var_typesSEXP, SEXP rt_info_SEXP, SEXP var_pos_info_SEXP, SEXP var_opts_SEXP, SEXP isGzippedSEXP, SEXP encodingSEXP, SEXP progressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_names(var_namesSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type var_types(var_typesSEXP);
    Rcpp::traits::input_parameter< List >::type rt_info_(rt_info_SEXP);
    Rcpp::traits::input_parameter< List >::type var_pos_info_(var_pos_info_SEXP);
    Rcpp::traits::input_parameter< List >::type var_opts_(var_opts_SEXP);
    Rcpp::traits::input_parameter< bool >::type isGzipped(isGzippedSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type encoding(encodingSEXP);
    Rcpp::traits::input_parameter< bool >::type progress(progressSEXP);
    rcpp_result_gen = Rcpp::wrap(read_long(filename, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_hipread_read_chunked_long", (DL_FUNC) &_hipread_read_chunked_long, 11},
    {"_hipread_read_long", (DL_FUNC) &_hipread_read_long, 9},
    {NULL, NULL, 0}
};

RcppExport void R_init_hipread(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
