# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_chunked_long <- function(filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress) {
    invisible(.Call(`_hipread_read_chunked_long`, filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress))
}

read_long <- function(filename, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress) {
    .Call(`_hipread_read_long`, filename, var_names, var_types, rt_info_, var_pos_info_, var_opts_, isGzipped, encoding, progress)
}

