# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_ipums_chunked_long <- function(filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_) {
    invisible(.Call(`_hipread_read_ipums_chunked_long`, filename, callback, chunksize, var_names, var_types, rt_info_, var_pos_info_, var_opts_))
}

